# Иморт библиотек

In [4]:
import numpy as np
import pandas as pd

# 1)

In [9]:
M = 1
s = 1
n = 1000

np.random.seed(42)
series = pd.Series(np.random.normal(loc=M, scale=s, size=n))
print("Сгенерированный массив")
display(series)

Сгенерированный массив

0      1.496714
1      0.861736
2      1.647689
3      2.523030
4      0.765847
         ...
995    0.718900
996    2.797687
997    1.640843
998    0.428821
999    1.572583
Length: 1000, dtype: float64

# 2)

In [15]:
numbers_in_range_1 = series[(series > M-s) & (series < M+s)].count()/n

print(f"Доля значений, находящихся  пределах [{M-s}; {M+s}] равна: {numbers_in_range_1} ")

Доля значений, находящихся  пределах [0; 2] равна: 0.698

# 3)

In [34]:
numbers_in_range_2 = series[(series > M-3*s) & (series < M+3*s)].count()/n

print(f"Доля значений, находящихся  пределах [{M-3*s}; {M+3*s}] равна: {numbers_in_range_2} ")
print("Доля значений, получившаяся эмпирически, совпадает с теоретической")

Доля значений, находящихся  пределах [-2; 4] равна: 0.997
Доля значений, получившаяся эмпирически, совпадает с теоретической

# 4)

In [38]:
sqrt_series = np.sqrt(series)

print("При попытке получить кадратный корень из значений, всплывает предупреждение из-за того, что в series присутствуют отрицательные значения, при попытке получить квадратный корень из таких чисел, numpy превращает их в nan значения")
print("Всего полученных nan значений, после попытки получить квадратный корень значений:", sqrt_series.isna().sum())
print(sqrt_series)

При попытке получить кадратный корень из значений, всплывает предупреждение из-за того, что в series присутствуют отрицательные значения, при попытке получить квадратный корень из таких чисел, numpy превращает их в nan значения
Всего полученных nan значений, после попытки получить квадратный корень значений: 147
0      1.223403
1      0.928297
2      1.283623
3      1.588405
4      0.875127
         ...
995    0.847880
996    1.672629
997    1.280954
998    0.654844
999    1.254027
Length: 1000, dtype: float64

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

# 5)

In [42]:
print("Среднее значение без nan:", sqrt_series.mean(skipna=True))

Среднее значение без nan: 1.065342961701133

# 6)

In [52]:
df = pd.DataFrame({"number": series, "root": sqrt_series})

print("Первые 6 строк созданного датафрейма:")
df.iloc[:6, :]

Первые 6 строк созданного датафрейма:

     number      root
0  1.496714  1.223403
1  0.861736  0.928297
2  1.647689  1.283623
3  2.523030  1.588405
4  0.765847  0.875127
5  0.765863  0.875136

# 7)

In [57]:
print("Значения в диапозоне [1.8; 1.9]\n")
df.query("root > 1.8 & root < 1.9")

Значения в диапозоне [1.8; 1.9]

       number      root
113  3.463242  1.860979
220  3.314659  1.820620
583  3.270693  1.808506
614  3.445752  1.856274
654  3.573360  1.890333
762  3.560085  1.886819
822  3.298898  1.816287
847  3.455300  1.858844
880  3.526932  1.878013