# Импорт библиотек

In [62]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# 1)

In [63]:
df = pd.read_csv('/content/athlete_events.csv')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

# 2)

In [14]:
display(df.info())
display(df["Medal"].unique())
print("\nУ колонок Height, Age и Weight имеются пропущенные неизвестные значения")
print("\nС колонкой Medal неоднозначно: либо значение неизвестно, либо у спортсмена нет медалей")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

None

array([nan, 'Gold', 'Bronze', 'Silver'], dtype=object)

У колонок Height, Age и Weight имеются пропущенные неизвестные значения

С колонкой Medal неоднозначно: либо значение неизвестно, либо у спортсмена нет медалей

# 3)

In [16]:
print("Статистическая информация: Age, Height, Weight")
display(df[['Age', 'Height', 'Weight']].describe())

Статистическая информация: Age, Height, Weight

                 Age         Height         Weight
count  261642.000000  210945.000000  208241.000000
mean       25.556898     175.338970      70.702393
std         6.393561      10.518462      14.348020
min        10.000000     127.000000      25.000000
25%        21.000000     168.000000      60.000000
50%        24.000000     175.000000      70.000000
75%        28.000000     183.000000      79.000000
max        97.000000     226.000000     214.000000

# 4.1)

In [30]:
id_1992 = df[df['Year'] == 1992]['Age'].idxmin()

age = df.iloc[id_1992]['Age']
name = df.iloc[id_1992]['Name']
discipline = df.iloc[id_1992]['Event']

print(f"Самому молодому участнику соревнования в 1992 году было {age} лет")
print(f"Имя самого молодого участника в 1992: {name}")
print(f"Дисциплина в которой участвовал самый молодой участник в 1992: {discipline}")

Самому молодому участнику соревнования в 1992 году было 11.0 лет
Имя самого молодого участника в 1992: Carlos Bienvenido Front Barrera
Дисциплина в которой участвовал самый молодой участник в 1992: Rowing Men's Coxed Eights

# 4.2)

In [33]:
 print("Все виды спорта олимпийских игр:")
 display(df['Sport'].unique().tolist())

Все виды спорта олимпийских игр:

['Basketball',
 'Judo',
 'Football',
 'Tug-Of-War',
 'Speed Skating',
 'Cross Country Skiing',
 'Athletics',
 'Ice Hockey',
 'Swimming',
 'Badminton',
 'Sailing',
 'Biathlon',
 'Gymnastics',
 'Art Competitions',
 'Alpine Skiing',
 'Handball',
 'Weightlifting',
 'Wrestling',
 'Luge',
 'Water Polo',
 'Hockey',
 'Rowing',
 'Bobsleigh',
 'Fencing',
 'Equestrianism',
 'Shooting',
 'Boxing',
 'Taekwondo',
 'Cycling',
 'Diving',
 'Canoeing',
 'Tennis',
 'Modern Pentathlon',
 'Figure Skating',
 'Golf',
 'Softball',
 'Archery',
 'Volleyball',
 'Synchronized Swimming',
 'Table Tennis',
 'Nordic Combined',
 'Baseball',
 'Rhythmic Gymnastics',
 'Freestyle Skiing',
 'Rugby Sevens',
 'Trampolining',
 'Beach Volleyball',
 'Triathlon',
 'Ski Jumping',
 'Curling',
 'Snowboarding',
 'Rugby',
 'Short Track Speed Skating',
 'Skeleton',
 'Lacrosse',
 'Polo',
 'Cricket',
 'Racquets',
 'Motorboating',
 'Military Ski Patrol',
 'Croquet',
 'Jeu De Paume',
 'Roque',
 'Alpinism',
 'Basque Pelota',
 'Aeronautics']

# 4.3)

In [38]:
query_43 = df[(df['Year'] == 2000) & (df['Sex'] == "F") & (df['Sport'] == "Tennis")]["Height"].mean()

print("Средний рост теннисисток участвовавших в 2000:", query_43)

Средний рост теннисисток участвовавших в 2000: 171.792

# 4.4)

In [41]:
query_44 = df[(df["Year"] == 2008) & (df["Team"] == "China") & (df['Sport'] == "Table Tennis") & (df['Medal'] == 'Gold')]['Name'].count()

print("Кол-во золотых медалей заработанных Китаем в 1998 в настольном теннисе:", query_44)

Кол-во золотых медалей заработанных Китаем в 1998 в настольном теннисе: 8

# 4.5)

In [45]:
sports_2004 = df[(df['Year'] == 2004) & (df['Season'] == 'Summer')]['Sport'].nunique()
sports_1988 = df[(df['Year'] == 1988) & (df['Season'] == 'Summer')]['Sport'].nunique()
print(f"На летних ОИ 2004 года было {sports_2004} видов спорта, а в 1988 - {sports_1988}.")
print(f"Изменение: {sports_2004 - sports_1988} видов спорта.")

На летних ОИ 2004 года было 34 видов спорта, а в 1988 - 27.
Изменение: 7 видов спорта.

# 4.6)

In [61]:
query_46 = df[(df['Year'] == 2014) & (df['Sport'] == 'Curling') & (df['Sex'] == 'M')]['Age']

fig = go.Figure()
fig.add_trace(go.Histogram(x=query_46, nbinsx = 10))
fig.show()

# 4.7)

In [66]:
query_46 = df[(df['Year'] == 2006) & (df['Season'] == 'Winter')]

country_stats = df.groupby('NOC').agg(MedalCount=('Medal', 'count'), AgeAverage=('Age', 'mean'))

print('Кол-во медалей и средний возраст по странам за 2006 год:')
display(country_stats[country_stats['MedalCount'] != 0])

Кол-во медалей и средний возраст по странам за 2006 год:

     MedalCount  AgeAverage
NOC
AFG           2   23.538462
AHO           1   26.589744
ALG          17   24.370642
ANZ          29   24.246914
ARG         274   25.897687
..          ...         ...
VIE           4   24.162338
WIF           5   26.200000
YUG         390   24.745721
ZAM           2   23.461039
ZIM          22   25.200647

[149 rows x 2 columns]

# 4.8)

In [71]:
pivot_table_2006 = pd.pivot_table(
    df,
    values='ID',
    index='NOC',
    columns='Medal',
    aggfunc='count',
    fill_value=0
)

print('Таблица по медалям за 2006 год:')
display(pivot_table_2006)

Таблица по медалям за 2006 год:

Medal  Bronze  Gold  Silver
NOC
AFG         2     0       0
AHO         0     0       1
ALG         8     5       4
ANZ         5    20       4
ARG        91    91      92
..        ...   ...     ...
VIE         0     1       3
WIF         5     0       0
YUG        93   130     167
ZAM         1     0       1
ZIM         1    17       4

[149 rows x 3 columns]