# Иморт библиотек

In [2]:
import pandas as pd
import numpy as np

# 1)

In [38]:
df = pd.read_csv('/content/telecom_churn.csv')

display(df.describe())
display(df.info())
df

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   object
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   object
 4   Voice mail plan         3333 non-null   object
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3333 non-null   float64
 7   Total day calls         3333 non-null   int64
 8   Total day charge        3333 non-null   float64
 9   Total eve minutes       3333 non-null   float64
 10  Total eve calls         3333 non-null   int64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3333 non-null   int64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3333 non-null   float64
 18  Customer service calls  3333 non-null   int64
 19  Churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

None

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

# 2)

In [7]:
print('Сколько клиентов пользуется сервисом и не пользуется:')
print(df['Churn'].value_counts())
print('Сколько клиентов пользуется сервисом и не пользуется в долях:')
print(df['Churn'].value_counts(normalize=True))

Сколько клиентов пользуется сервисом и не пользуется:
Churn
False    2850
True      483
Name: count, dtype: int64
Сколько клиентов пользуется сервисом и не пользуется в процентном соотношении:
Churn
False    0.855086
True     0.144914
Name: proportion, dtype: float64

# 3)

In [19]:
df['Mean call duration'] = (df['Total day minutes'] / df['Total day calls'] + df['Total eve minutes'] / df['Total eve calls'] + df['Total night minutes'] / df['Total night calls']) / 3

print("Датафрейм с колонкой 'Mean call duration':")
display(df)

Датафрейм с колонкой 'Mean call duration':

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,Mean call duration
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False,2.364317
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False,1.893927
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False,1.600122
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False,2.377557
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False,1.411808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,18.32,279.1,83,12.56,9.9,6,2.67,2,False,2.367180
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,13.04,191.3,123,8.61,9.6,4,2.59,3,False,2.799587
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,24.55,191.9,91,8.64,14.1,6,3.81,2,False,2.915606
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,...,13.57,139.2,137,6.26,5.0,10,1.35,2,False,1.650750
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,22.60,241.4,77,10.86,13.7,4,3.70,0,False,2.817361

# 4)

In [20]:
print("Среднее время звонка по значению поля Churn:")
print(df.groupby(['Churn'])['Mean call duration'].mean())
print("\nСущественная разница отсутстует")

Среднее время звонка по значению поля Churn:
Churn
False    1.999777
True     2.159687
Name: Mean call duration, dtype: float64

Существенная разница отсутстует

# 5)

In [23]:
avg_calls_service = df.groupby('Churn')['Customer service calls'].mean()
print("Среднее количество звонков в службу поддержки:")
print(avg_calls_service)
print(f"\nСущественная разница присутствует")

Среднее количество звонков в службу поддержки:
Churn
False    1.449825
True     2.229814
Name: Customer service calls, dtype: float64

Существенная разница присутствует

# 6)

In [29]:
crosstab_service_calls = pd.crosstab(df['Customer service calls'], df['Churn'], normalize='index')

print("Таблица сопряженности Customer service calls и Churn:")
display(crosstab_service_calls)
print("\nОт четырех звонках процент оттока станоится значительным 45%")

Таблица сопряженности Customer service calls и Churn:

Churn                      False     True
Customer service calls
0                       0.868006  0.131994
1                       0.896698  0.103302
2                       0.885375  0.114625
3                       0.897436  0.102564
4                       0.542169  0.457831
5                       0.393939  0.606061
6                       0.363636  0.636364
7                       0.444444  0.555556
8                       0.500000  0.500000
9                       0.000000  1.000000

При четырех звонках процент оттока станоится значительным 45%

# 7)

In [31]:
crosstab_international_plan = pd.crosstab(df['International plan'], df['Churn'], normalize='index')

print("Таблица сопряженности International plan и Churn:")
display(crosstab_international_plan)
print("\nПроцент оттока пользователей при использования международного роуминга больше чем при не использовании")

Таблица сопряженности International plan и Churn:

Churn                  False     True
International plan
No                  0.885050  0.114950
Yes                 0.575851  0.424149

Процент оттока пользователей при использования международного роуминга больше чем при не использовании

# 8)

In [37]:
df['Predicted churn'] = (df['International plan'] == 'Yes') | (df['Customer service calls'] >= 4)

false_positive = ((df['Churn'] == False) & (df['Predicted churn'] == True)).sum()
false_positive_rate = false_positive / (df['Churn'] == False).sum()

false_negative = ((df['Churn'] == True) & (df['Predicted churn'] == False)).sum()
false_negative_rate = false_negative / (df['Churn'] == True).sum()

print("Всего ложноположительных предсказаний:", false_positive)
print("Доля ложноположительных предсказаний:", false_positive_rate)
print("\nВсего ложноположительных предсказаний:", false_negative)
print("Доля ложнонегативных предсказаний:", false_negative_rate)

Всего ложноположительных предсказаний: 306
Доля ложноположительных предсказаний: 0.10736842105263159

Всего ложноположительных предсказаний: 227
Доля ложнонегативных предсказаний: 0.4699792960662526