# Импорт библиотек

In [1]:
import pandas as pd
import numpy as np

# 1)

In [8]:
generation = pd.read_csv('/content/global-electricity-generation.csv')
consumption = pd.read_csv('/content/global-electricity-consumption.csv')

generation = generation.set_index('Country')
consumption = consumption.set_index('Country')

for col in generation.columns:
    generation[col] = pd.to_numeric(generation[col], errors='coerce')
for col in consumption.columns:
    consumption[col] = pd.to_numeric(consumption[col], errors='coerce')

print('Глобальное производство электроэнергии:')
display(generation.head())
print('Глобальное потребление электроэнергии:')
display(consumption.head())

Глобальное производство электроэнергии:

,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Algeria,17.199,18.267,18.703,18.090,19.1240,19.7390,21.4480,23.2820,23.88952,25.03064,...,53.98450,56.31340,60.39972,64.68244,66.755040,71.49546,72.10903,76.68500,72.735913,77.530727
Angola,1.283,1.332,1.342,1.347,1.3770,1.3310,1.5200,1.3000,1.40402,1.59074,...,6.03408,7.97606,9.21666,9.30914,10.203511,10.67604,12.83194,15.40000,16.600000,16.429392
Benin,0.023,0.024,0.048,0.029,0.0487,0.0517,0.0597,0.0677,0.07908,0.06216,...,0.04612,0.08848,0.22666,0.31056,0.260040,0.31150,0.19028,0.20170,0.226080,0.241097
Botswana,1.088,1.027,1.044,1.047,0.7590,0.8700,1.0260,1.0430,0.89018,0.94940,...,0.33000,0.86868,2.17628,2.79104,2.529840,2.84380,2.97076,3.04690,2.051440,2.182348
Burkina Faso,0.190,0.205,0.206,0.232,0.2630,0.2820,0.3120,0.3480,0.31800,0.32700,...,0.86834,0.98268,1.11808,1.43986,1.550900,1.64602,1.64640,1.72552,1.647133,1.761210

Глобальное потребление электроэнергии:

,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Algeria,14.03500,14.03900,14.36500,14.47400,15.17200,15.36500,16.90500,18.49200,19.71552,20.64764,...,42.86750,45.20140,49.205720,53.45544,55.823040,60.283460,62.114030,66.646000,63.694903,68.663379
Angola,1.01300,1.06200,1.07100,1.07400,1.08500,1.21600,1.32800,1.10600,1.19302,1.35274,...,5.33508,7.05006,8.148660,8.23114,9.036511,9.468667,11.384079,13.658591,14.754764,14.560491
Benin,0.22900,0.22100,0.25200,0.24200,0.27870,0.27970,0.27070,0.31470,0.39008,0.39516,...,0.93312,0.93648,0.933660,1.08156,1.061040,1.125821,1.187964,0.929700,0.524080,0.523383
Botswana,1.09184,1.11411,1.28092,1.31371,1.39087,1.55710,1.57100,1.74900,1.71218,2.02240,...,3.20900,3.34768,3.605280,3.73004,3.615840,3.552800,3.651212,4.162138,3.222130,3.353038
Burkina Faso,0.17670,0.19065,0.19158,0.21576,0.24459,0.26226,0.29016,0.32364,0.26900,0.32970,...,1.24784,1.35648,1.431962,1.69966,1.997400,2.067920,2.264800,2.651386,2.467133,2.642688

# 2)

In [3]:
generation_five_years = generation.iloc[:,-5:].mean()
consumption_five_years = consumption.iloc[:,-5:].mean()

print('Среднее глобальное производство электроэнергии за последние 5 лет:')
display(generation_five_years)
print('Среднее глобальное потребление электроэнергии за последние 5 лет:')
display(consumption_five_years)

Среднее глобальное производство электроэнергии за последние 5 лет:

2017    115.888612
2018    119.770536
2019    121.504679
2020    121.488009
2021    128.113961
dtype: float64

Среднее глобальное потребление электроэнергии за последние 5 лет:

2017    104.682977
2018    108.437420
2019    110.210399
2020    110.413272
2021    116.759018
dtype: float64

# 3.1)

In [10]:
total_consumption_per_year = consumption.sum(axis=0)

print("Суммарное потребление электроэнергии за каждый год")
display(total_consumption_per_year)

Суммарное потребление электроэнергии за каждый год

1992    10569.016201
1993    10854.562919
1994    11104.653834
1995    11476.479041
1996    11805.865473
1997    12122.033114
1998    12419.808873
1999    12685.754131
2000    13230.249502
2001    13486.489704
2002    13938.778793
2003    14455.562329
2004    15128.097979
2005    15725.982376
2006    16438.213771
2007    17205.119808
2008    17477.471007
2009    17435.687358
2010    18748.160724
2011    19438.823496
2012    19918.254954
2013    20573.096414
2014    20981.239762
2015    21400.017770
2016    22022.686879
2017    22716.206102
2018    23530.920048
2019    23915.656498
2020    23959.680109
2021    25336.707010
dtype: float64

# 3.2)

In [80]:
max_generation = generation.max().max()

print("Максимальное количество энергии произведенное за год:", max_generation)

Максимальное количество энергии произведенное за год: 8151.518231

# 3.3)

In [79]:
mean_last_five_years_generation = generation.iloc[:,-5:].mean(axis=1)
generation_more_than_500 = mean_last_five_years_generation[mean_last_five_years_generation > 500]

print("Страны произодящие в среднем более 500 млрд. кВт*ч за последние 5 лет:")
display(generation_more_than_500)

Страны произодящие в среднем более 500 млрд. кВт*ч за последние 5 лет:

Country
Russia           1059.992996
France            533.218951
Germany           581.558404
China            7190.022571
India            1595.249269
Japan             983.880140
South Korea       558.355090
Canada            631.606399
United States    4130.269086
Brazil            614.184862
dtype: float64

# 3.4)

In [78]:
mean_last_five_years_consumption = consumption.iloc[:,-5:].mean(axis=1)
quantile_90 = mean_last_five_years_consumption.quantile(0.9)
max_10_percent_consumption_countries = mean_last_five_years_consumption[mean_last_five_years_consumption > quantile_90]

print("10% стран, которые потребляют больше всего электроэнергии ежегодно в среднем за 5 лет:")
display(max_10_percent_consumption_countries)

10% стран, которые потребляют больше всего электроэнергии ежегодно в среднем за 5 лет:

Country
South Africa       200.649088
Russia             946.678796
France             445.223264
Germany            520.234640
Italy              296.443217
Spain              240.371533
Turkiye            263.490688
United Kingdom     303.543997
Australia          238.597478
China             6846.206993
India             1330.936242
Indonesia          256.329860
Japan              940.321860
South Korea        539.511605
Taiwan             265.071970
Vietnam            206.115838
Iran               282.508003
Saudi Arabia       324.517126
Canada             547.319651
Mexico             285.825534
United States     3957.497224
Brazil             539.933482
dtype: float64

# 3.5)

In [77]:
counry_generation_with_10x_growth = generation[generation.loc[:, '2021'] / generation.loc[:, '1992'] > 10].index.tolist()

print("Список стран, которые увеличили производство электроэнергии в 2021 году по сравнению с 1992 годом более, чем в 10 раз:")
display([country.lstrip() for country in counry_generation_with_10x_growth])

Список стран, которые увеличили производство электроэнергии в 2021 году по сравнению с 1992 годом более, чем в 10 раз:

['Angola',
 'Benin',
 'Equatorial Guinea',
 'Ethiopia',
 'Lesotho',
 'Mali',
 'Mauritania',
 'Mozambique',
 'Namibia',
 'Sudan',
 'Cambodia',
 'China',
 'Laos',
 'Maldives',
 'Vietnam',
 'Turks and Caicos Islands']

# 3.6)

In [76]:
mask_countries_consumption_more_100_less_than_generation = (consumption.sum(axis=1) > 100) & (generation.sum(axis=1) < consumption.sum(axis=1))
print("Список стран, которые в сумме за все годы потратили больше 100 млрд. кВт*ч электроэнергии и при этом произвели меньше, чем потратили:")
display([country.lstrip() for country in generation[mask_countries_consumption_more_100_less_than_generation].index.tolist()])

Список стран, которые в сумме за все годы потратили больше 100 млрд. кВт*ч электроэнергии и при этом произвели меньше, чем потратили:

['Zimbabwe',
 'Belarus',
 'Moldova',
 'Belgium',
 'Croatia',
 'Finland',
 'Hungary',
 'Italy',
 'Latvia',
 'Luxembourg',
 'Netherlands',
 'North Macedonia',
 'Hong Kong']

# 3.7)

In [75]:
country_spent_most_in_2020 = consumption['2020'].idxmax().lstrip()
country_num_spent_most_in_2020 = consumption['2020'].max()
print(f"Страна, потратившая наибольшее количество электроэнергии в 2020 году: {country_spent_most_in_2020}, {country_num_spent_most_in_2020}")

Страна, потратившая наибольшее количество электроэнергии в 2020 году: China, 7115.077185